name: Schedule - Cleanup

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  cleanup_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        id: app-token
        with:
          app-id: ${{ secrets.PRIVATE_APP_ID }}
          private-key: ${{ secrets.PRIVATE_APP_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Cleanup workflow stale runs
        uses: Mattraks/delete-workflow-runs@feeb82053ea847a97fe4ee2aa314c94eac0eff04 # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "0"
          delete_run_by_conclusion_pattern: "cancelled,skipped"
      - name: Cleanup workflow success runs
        uses: Mattraks/delete-workflow-runs@feeb82053ea847a97fe4ee2aa314c94eac0eff04 # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "5"
          delete_run_by_conclusion_pattern: "success"
      - name: Clenaup workflow failure runs
        uses: Mattraks/delete-workflow-runs@feeb82053ea847a97fe4ee2aa314c94eac0eff04 # v2
        with:
          token: "${{ steps.app-token.outputs.token }}"
          repository: "${{ github.repository }}"
          retain_days: "0"
          keep_minimum_runs: "1"
          delete_run_by_conclusion_pattern: "action_required,failure"

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c # v1
